### ISSUE TITLE
出现错误提示

### ISSUE THREAD

**Issue by tonylxt** [JZPPP/firstlearn#1]
AttributeError: 'NoneType' object has no attribute 'string'
PS D:\pythonProject\firstlearn-main> & C:/Users/AppData/Local/Programs/Python/Python312/python.exe d:/pythonProject/firstlearn-main/main.py    
Traceback (most recent call last):
  File "d:\pythonProject\firstlearn-main\main.py", line 51, in <module>
    learn_time_text = re.search(r'var learnTime\s*=\s*(\{.*?\});', script_tag.string, re.DOTALL).group(1)

**Comment by tonylxt** [comment]
这里聊太费劲了，方便在你的主页加联系方式吗

**Comment by tonylxt** [comment]
尝试着更新了10点的版本，还是出现同样的问题

**Comment by JZPPP** [comment]
参考视频链接
https://www.bilibili.com/video/BV1j24EeBEPY/

**Comment by tonylxt** [comment]
问题解决了，一切正常
